### ISSUE TITLE
Error: invalid block number on several elements

### ISSUE THREAD

**Issue by ice09** [gobitfly/etherchain-light#12]
#7 has been fixed, but with the current version I get ```Error: invalid block number``` again with clicks on almost every element: the miner hash, account hashes, etc.

Simple setup, PoA modeled after DemoPoA-tutorial of parity, all parameters set correctly from start of each of the two nodes. ipcpath points to first node.

```
Error: invalid block number
    at Object.InvalidResponse (/home/hal9000/parity/etherchain-light/node_modules/web3/lib/web3/errors.js:35:16)
    at Object.<anonymous> (/home/hal9000/parity/etherchain-light/node_modules/web3/lib/web3/requestmanager.js:86:36)
    at /home/hal9000/parity/etherchain-light/node_modules/web3/lib/web3/ipcprovider.js:66:44
    at Array.forEach (native)
    at Socket.<anonymous> (/home/hal9000/parity/etherchain-light/node_modules/web3/lib/web3/ipcprovider.js:50:47)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at Pipe.onread (net.js:548:20)
```

**Comment by gobitfly** [comment]
Have you authored / mined any blocks on your chain? If there are no blocks created yet you will most likely receive such errors.

**Comment by ice09** [comment]
yes, they are also shown in the list and they are correct, just the detail view is not correct.

**Comment by gobitfly** [comment]
Sorry but there seems to be something wrong with your local setup. I went trough the Parity PoA demo instructions and was unable to reproduce the issue you are describing.

**Comment by ice09** [comment]
Ok, but just for reference, using an older version, everything works, just when I use the current head, I get the error. I am using Ubuntu 16.04 LTS, node 5.11.0, npm 4.2.0. Replication is actually exactly what you did, following DemoPoA and afterwards installing etherchain-light, configuring the correct ipcpath. I can see all blocks, all transactions etc., but on clicking a miner hash, an account etc. I get this error. Doing the same in the older version, everything works as expected.

**Comment by gobitfly** [comment]
With steps to reproduce I meant that you should add the config files that you are using as well as the command line args you use to start the nodes to the ticket.

**Comment by ice09** [comment]
config etherchain (config.js), local
```
var web3 = require('web3');
var net = require('net');

var config = function () {
  
  this.logFormat = "combined";
  this.ipcPath = '/home/radgon/dev/ethereum/2017/parity/node2/data/jsonrpc.ipc';
  this.provider = new web3.providers.IpcProvider(this.ipcPath, net);
  
  this.bootstrapUrl = "https://maxcdn.bootstrapcdn.com/bootswatch/3.3.7/yeti/bootstrap.min.css";
  
  this.names = {
  }
  
}

module.exports = config;
```

node0.toml, remote:
```
[parity]
chain = "demo-spec.json"
base_path = "/home/radgon/dev/ethereum/2017/parity/node0/data"
[network]
port = 30300
[rpc]
disable = false
port = 8540
cors = "*"
apis = ["web3", "eth", "net", "personal", "parity", "parity_set", "traces", "rpc", "parity_accounts"]
[ui]
port = 8180
[dapps]
port = 8080
[account]
password = ["node.pwds"]
[mining]
engine_signer = "0x00Bd138aBD70e2F00903268F3Db08f2D25677C9e"
usd_per_tx = "0"
reseal_on_txs = "none"
```

startNode0.sh, remote:
```
parity --config node0.toml --tracing=on --fat-db=on --pruning=archive --jsonrpc-hosts="all"
```

node1.toml, remote
```[parity]
chain = "demo-spec.json"
base_path = "/home/radgon/dev/ethereum/2017/parity/node1/data"
[network]
port = 30301
[rpc]
disable = false
port = 8541
cors = "*"
apis = ["web3", "eth", "net", "personal", "parity", "parity_set", "traces", "rpc", "parity_accounts"]
[ui]
port = 8181
[dapps]
port = 8081
[account]
password = ["node.pwds"]
[mining]
engine_signer = "0x00Aa39d30F0D20FF03a22cCfc30B7EfbFca597C2"
usd_per_tx = "0"
reseal_on_txs = "none"
```

startNode1.sh, remote
```
parity --config node1.toml --tracing=on --fat-db=on --pruning=archive
```

node2.toml, local
```
[parity]
chain = "demo-spec.json"
base_path = "/home/radgon/dev/ethereum/2017/parity/node2/data"
[network]
port = 30302
[rpc]
disable = false
port = 8542
cors = "*"
apis = ["web3", "eth", "net", "personal", "parity", "parity_set", "traces", "rpc", "parity_accounts"]
[ui]
port = 8182
[dapps]
port = 8082
```

startNode2.sh, local
```
parity --config node2.toml --tracing=on --fat-db=on --pruning=archive
```
