### ISSUE TITLE
Issue connecting over IPC

### ISSUE THREAD

**Issue by chevdor** [gobitfly/etherchain-light#2]
`this.ipcPath = "$HOME/.parity/jsonrpc.ipc";`

```
$ ls -al $HOME/.parity/jsonrpc.ipc
srwxr-xr-x 1 pi pi 0 Mar 10 18:34 /home/pi/.parity/jsonrpc.ipc
````

```
$ PORT=3080 npm start

> etherchain-light@0.0.0 start /var/www/dev/etherchain-light
> node ./bin/www

IPC Connection Error { Error: connect ENOENT $HOME/.parity/jsonrpc.ipc
    at Object.exports._errnoException (util.js:1022:11)
    at exports._exceptionWithHostPort (util.js:1045:20)
    at PipeConnectWrap.afterConnect [as oncomplete] (net.js:1087:14)
  code: 'ENOENT',
  errno: 'ENOENT',
  syscall: 'connect',
  address: '$HOME/.parity/jsonrpc.ipc' }
Error updating node status: Error: CONNECTION ERROR: Couldn't connect to node on IPC.
    at Object.InvalidConnection (/var/www/dev/etherchain-light/node_modules/web3/lib/web3/errors.js:28:16)
    at IpcProvider._timeout (/var/www/dev/etherchain-light/node_modules/web3/lib/web3/ipcprovider.js:150:48)
    at Socket.<anonymous> (/var/www/dev/etherchain-light/node_modules/web3/lib/web3/ipcprovider.js:38:15)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at emitErrorNT (net.js:1278:8)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)

```

**Comment by gobitfly** [comment]
Use process.env["HOME"] instead of $HOME. $HOME is a shell variable and is not resolved when included in a JS string.

**Comment by chevdor** [comment]
yep, I that´s the issue.
