### ISSUE TITLE
(Problem) Issue verifying a contract

### ISSUE THREAD

**Issue by rstormsf** [gobitfly/etherchain-light#30]
1. Deploy any contract with 0.4.18
2. Try to verify it
```
Error during contract verification: module.js:472 throw err; ^ Error: Cannot find module './solc-bin/bin/soljson-v0.4.18-nightly.2017.10.16+commit.dbc8655b.js' at Function.Module._resolveFilename (module.js:470:15) at Function.Module._load (module.js:418:25) at Module.require (module.js:498:17) at require (internal/module.js:20:19) at Object.<anonymous> (/home/pool/etherchain-light/utils/compile.js:56:39) at Module._compile (module.js:571:32) at Object.Module._extensions..js (module.js:580:10) at Module.load (module.js:488:32) at tryModuleLoad (module.js:447:12) at Function.Module._load (module.js:439:3)
```

**Comment by ppratscher** [comment]
Did you initialize the solc submodule in order to retrieve all complier versions?

**Comment by rstormsf** [comment]
I used your deployed kovan chain explorer

**Comment by ppratscher** [comment]
Fixed by updating the git submodule on the server.
