### ISSUE TITLE
Error connecting to parity client 1.8.10

### ISSUE THREAD

**Issue by jersteth** [gobitfly/etherchain-light#43]
I am having an issue when starting etherchain, also when launched from Docker, so I suspect it's maybe related to the version of parity? Any idea how to fix this? 

npm start

> etherchain-light@0.0.0 start /Users/jeroen/dev/mola/etherchain-light
> node ./bin/www

timers.js:394
    throw new TypeError('"msecs" argument must be a number');
    ^

TypeError: "msecs" argument must be a number
    at Object.exports.enroll (timers.js:394:11)
    at Socket.setTimeout (net.js:388:12)
    at ClientRequest.<anonymous> (_http_client.js:727:10)
    at Object.onceWrapper (events.js:314:30)
    at emitOne (events.js:120:20)
    at ClientRequest.emit (events.js:210:7)
    at tickOnSocket (_http_client.js:652:7)
    at onSocketNT (_http_client.js:668:5)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! etherchain-light@0.0.0 start: `node ./bin/www`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the etherchain-light@0.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by jersteth** [comment]
Nevermind ..
