### ISSUE TITLE
Crash if open URL tranzaction type create

### ISSUE THREAD

**Issue by PavelSheremetev** [gobitfly/etherchain-light#60]
when opening a transaction link with a type create an application crashes with the error:

```
/var/lib/parity/etherchain-light/node_modules/levelup/lib/levelup.js:141
    throw new ReadError('get() requires a key argument')
    ^
ReadError: get() requires a key argument
    at LevelUP.get (/var/lib/parity/etherchain-light/node_modules/levelup/lib/levelup.js:141:11)
    at /var/lib/parity/etherchain-light/routes/tx.js:86:10
    at nextTask (/var/lib/parity/etherchain-light/node_modules/async/dist/async.js:5324:14)
    at next (/var/lib/parity/etherchain-light/node_modules/async/dist/async.js:5331:9)
    at /var/lib/parity/etherchain-light/node_modules/async/dist/async.js:969:16
    at Object.callback (/var/lib/parity/etherchain-light/routes/tx.js:83:9)
    at /var/lib/parity/etherchain-light/node_modules/web3/lib/web3/method.js:142:25
    at Object.<anonymous> (/var/lib/parity/etherchain-light/node_modules/web3/lib/web3/requestmanager.js:89:9)
    at /var/lib/parity/etherchain-light/node_modules/web3/lib/web3/ipcprovider.js:66:44
    at Array.forEach (<anonymous>)

```

**Comment by illya-havsiyevych** [comment]
can confirm the same
```
/home/ubuntu/etherchain-light/node_modules/levelup/lib/levelup.js:141
    throw new ReadError('get() requires a key argument')
    ^
ReadError: get() requires a key argument
    at LevelUP.get (/home/ubuntu/etherchain-light/node_modules/levelup/lib/levelup.js:141:11)
    at /home/ubuntu/etherchain-light/routes/tx.js:86:10
    at nextTask (/home/ubuntu/etherchain-light/node_modules/async/dist/async.js:5324:14)
    at next (/home/ubuntu/etherchain-light/node_modules/async/dist/async.js:5331:9)
    at /home/ubuntu/etherchain-light/node_modules/async/dist/async.js:969:16
    at Object.callback (/home/ubuntu/etherchain-light/routes/tx.js:83:9)
    at /home/ubuntu/etherchain-light/node_modules/web3/lib/web3/method.js:142:25
    at Object.<anonymous> (/home/ubuntu/etherchain-light/node_modules/web3/lib/web3/requestmanager.js:89:9)
    at /home/ubuntu/etherchain-light/node_modules/web3/lib/web3/ipcprovider.js:66:44
    at Array.forEach (<anonymous>)
```

**Comment by illya-havsiyevych** [comment]
maybe this is because of Node `v8.10.x`

**Comment by protocold** [comment]
I tried with Node v10.16 and it is the same. Which version of Node should we try?
