### ISSUE TITLE
etherchain-light should work in PoA-mode

### ISSUE THREAD

**Issue by ice09** [gobitfly/etherchain-light#7]
possible dup to #6 

etherchain-light shows this error after installing PoA according to https://github.com/paritytech/parity/wiki/Demo-PoA-tutorial

```
Error: invalid block number
    at Object.module.exports.InvalidResponse (/home/radgon/dev/ethereum/2017/parity/etherchain-light/node_modules/web3/lib/web3/errors.js:35:16)
    at Object.<anonymous> (/home/radgon/dev/ethereum/2017/parity/etherchain-light/node_modules/web3/lib/web3/requestmanager.js:86:36)
    at /home/radgon/dev/ethereum/2017/parity/etherchain-light/node_modules/web3/lib/web3/ipcprovider.js:66:44
    at Array.forEach (native)
    at Socket.<anonymous> (/home/radgon/dev/ethereum/2017/parity/etherchain-light/node_modules/web3/lib/web3/ipcprovider.js:50:47)
    at emitOne (events.js:90:13)
    at Socket.emit (events.js:182:7)
    at readableAddChunk (_stream_readable.js:153:18)
    at Socket.Readable.push (_stream_readable.js:111:10)
    at Pipe.onread (net.js:534:20)
```

**Comment by gobitfly** [comment]
Thanks for reporting this issue. It has been fixed with the latest commit.
